export const openingHooks = [
  "I am writing to express my strong support for protecting the MassBay Forest and Centennial Park parcel.",
  "As a local resident, I am reaching out to urge you to preserve the MassBay Forest property.",
  "I am contacting you today to advocate for the permanent protection of the MassBay Forest.",
  "Please consider this letter a formal request to save the Centennial Park parcel from development.",
  "I am writing to you with a sense of urgency regarding the future of the MassBay Forest.",
  "It is with great concern for our local environment that I write to you about MassBay Forest.",
  "I urge you to take immediate action to protect the MassBay Forest and Centennial Park parcel.",
  "I am adding my voice to the growing number of residents calling for the preservation of MassBay Forest.",
  "Protecting the MassBay Forest is a critical issue for our community, which is why I am writing to you today.",
  "I am writing to respectfully request your support in saving the MassBay Forest from development.",
  "The future of the MassBay Forest is at stake, and I am writing to ask for your help in protecting it.",
  "I am reaching out to emphasize the importance of preserving the MassBay Forest for future generations.",
  "Please stand with our community in protecting the invaluable MassBay Forest and Centennial Park parcel.",
  "I am writing to share my deep concern about the potential development of the MassBay Forest.",
  "As someone who cares deeply about our local green spaces, I urge you to protect MassBay Forest.",
  "I am writing to ask that you prioritize the conservation of the MassBay Forest and Centennial Park parcel.",
  "The preservation of MassBay Forest is essential, and I am writing to request your leadership on this issue.",
  "I am contacting you to voice my strong opposition to any development on the MassBay Forest property.",
  "Please take action to ensure the permanent protection of the MassBay Forest and Centennial Park parcel.",
  "I am writing to implore you to save the MassBay Forest, a vital natural resource for our community.",
  "I am reaching out today because the protection of MassBay Forest is an issue of paramount importance.",
  "I write to you today to champion the preservation of the MassBay Forest and Centennial Park parcel.",
  "It is imperative that we protect the MassBay Forest, which is why I am contacting you now.",
  "I am writing to urge your administration to secure the conservation of the MassBay Forest.",
  "Please help us safeguard the MassBay Forest and Centennial Park parcel from irreversible development.",
  "I am adding my name to the list of citizens demanding the protection of MassBay Forest.",
  "I am writing to request your immediate intervention to preserve the MassBay Forest property.",
  "The MassBay Forest is a local treasure, and I am writing to ask that you help protect it.",
  "I am reaching out to respectfully urge you to support the conservation of MassBay Forest.",
  "I am writing to express my unwavering support for the permanent preservation of MassBay Forest."
];

export const communityThemeSentences = [
  "This forest provides a strong sense of community to the many repeat visitors who walk its trails.",
  "The MassBay Forest is more than just trees; it is a gathering place that fosters a deep sense of community.",
  "Repeat visitors to the forest share a strong bond, creating a vibrant community centered around this natural space.",
  "The trails of MassBay Forest offer a unique space where neighbors connect, building a strong community spirit.",
  "Preserving this land means preserving the strong sense of community it provides to its countless regular visitors.",
  "The forest serves as a vital community hub for those who repeatedly seek out its peaceful trails.",
  "A strong sense of community thrives among the repeat visitors who cherish the MassBay Forest.",
  "This natural area is essential for maintaining the strong community ties formed by its frequent visitors.",
  "The MassBay Forest brings people together, offering a strong sense of community to all who visit regularly.",
  "Protecting this space is about protecting the community of repeat visitors who rely on it.",
  "The shared experience of enjoying the MassBay Forest creates a powerful sense of community among locals.",
  "Regular visitors to the forest have built a strong, supportive community that depends on this land.",
  "The forest is a cornerstone of our local community, especially for those who visit it time and time again.",
  "A palpable sense of community exists among the many people who repeatedly walk the trails of MassBay Forest.",
  "This land is a sanctuary that nurtures a strong sense of community for its dedicated repeat visitors.",
  "The MassBay Forest is a place where community is forged among those who frequently explore its paths.",
  "We must protect the strong sense of community that the forest provides to its many regular visitors.",
  "The forest's trails are a lifeline for the strong community of repeat visitors who love this space.",
  "A deep sense of community is shared by the countless individuals who repeatedly visit the MassBay Forest.",
  "This forest is a vital asset that fosters a strong community among its frequent and passionate visitors.",
  "The MassBay Forest is a unifying force, creating a strong sense of community for its repeat visitors.",
  "Protecting the forest ensures the survival of the strong community that has grown around it.",
  "The regular visitors to MassBay Forest form a strong community united by their love for this natural space.",
  "This forest is a shared treasure that provides a profound sense of community to its repeat visitors.",
  "The strong sense of community found among the forest's frequent visitors is something we cannot afford to lose."
];

export const transitions = [
  "Furthermore,",
  "In addition,",
  "Moreover,",
  "Additionally,",
  "Beyond this,",
  "Equally important,",
  "It is also crucial to note that",
  "Another key point is that",
  "We must also consider that",
  "Along with this,",
  "Not only that, but",
  "To add to this,",
  "Similarly,",
  "Likewise,",
  "As well,",
  "On top of this,",
  "Importantly,",
  "Significantly,",
  "Notably,",
  "It should also be highlighted that",
  "Another critical factor is that",
  "We cannot ignore that",
  "It is equally vital to remember that",
  "Coupled with this,",
  "In the same vein,",
  "A further consideration is that",
  "This is compounded by the fact that",
  "Adding to this urgency,",
  "It is also worth mentioning that",
  "Another compelling reason is that"
];

export const askSentences = [
  "I respectfully ask that you take all necessary steps to protect this parcel.",
  "Please do everything in your power to ensure this land is conserved.",
  "I urge you to support the permanent protection of the MassBay Forest.",
  "I am asking for your commitment to saving this vital natural resource.",
  "Please stand with our community and protect the Centennial Park parcel.",
  "I call upon you to prioritize the conservation of this irreplaceable land.",
  "I request your leadership in securing the future of the MassBay Forest.",
  "Please take immediate action to prevent the development of this property.",
  "I urge you to champion the preservation of the MassBay Forest and Centennial Park parcel.",
  "I am asking you to use your influence to protect this crucial green space.",
  "Please help us ensure that the MassBay Forest remains undeveloped forever.",
  "I respectfully urge you to support efforts to conserve this important parcel.",
  "I ask that you make the protection of MassBay Forest a top priority.",
  "Please work with our community to save the Centennial Park parcel from development.",
  "I call on you to take a stand for the permanent preservation of this land.",
  "I request your assistance in protecting the MassBay Forest for future generations.",
  "Please do not let this invaluable natural resource be lost to development.",
  "I urge you to take decisive action to conserve the MassBay Forest property.",
  "I am asking for your help in securing a conservation restriction for this land.",
  "Please support the community's efforts to protect the MassBay Forest and Centennial Park parcel."
];

export const gratitudeClosings = [
  "Thank you for your time and consideration of this important matter.",
  "I appreciate your attention to this critical issue.",
  "Thank you for your dedication to our community and its natural resources.",
  "I am grateful for your leadership and support in protecting our environment.",
  "Thank you for taking the time to read my letter and consider my request.",
  "I appreciate your commitment to preserving the character of our town.",
  "Thank you for your service and your attention to the MassBay Forest.",
  "I am thankful for your efforts to protect our local green spaces.",
  "Thank you for considering the voices of the community on this issue.",
  "I appreciate your hard work and dedication to our shared environment.",
  "Thank you for your thoughtful consideration of this urgent request.",
  "I am grateful for your willingness to listen to the concerns of residents.",
  "Thank you for your ongoing support for conservation efforts in our area.",
  "I appreciate your leadership in safeguarding our natural heritage.",
  "Thank you for your time, and I look forward to your positive action.",
  "I am thankful for your commitment to the well-being of our community.",
  "Thank you for your attention to the preservation of the MassBay Forest.",
  "I appreciate your dedication to making our town a better place to live.",
  "Thank you for considering this vital request to protect our local environment.",
  "I am grateful for your time and your service to our community."
];

export const signoffs = [
  "Sincerely,",
  "Respectfully,",
  "Best regards,",
  "Kind regards,",
  "Yours truly,",
  "With appreciation,",
  "With gratitude,",
  "Respectfully yours,",
  "Yours sincerely,",
  "Thank you,"
];

export const toneAdjusters = {
  Respectful: [
    "I hope you will consider",
    "I respectfully suggest",
    "It would be deeply appreciated if",
    "I kindly request",
    "Please consider",
    "I trust you will weigh",
    "I am hopeful that",
    "With respect, I ask",
    "I would be grateful if",
    "I humbly request"
  ],
  Firm: [
    "We must insist that",
    "It is unacceptable to allow",
    "You have a responsibility to",
    "The community demands",
    "We expect action on",
    "It is non-negotiable that",
    "We cannot compromise on",
    "You must ensure that",
    "It is your duty to",
    "We firmly request"
  ],
  Urgent: [
    "Time is running out to",
    "We must act immediately to",
    "This is a critical moment for",
    "Urgent action is required to",
    "We cannot afford to wait on",
    "The time to act is now regarding",
    "Immediate intervention is needed for",
    "We are out of time to save",
    "This emergency requires you to",
    "Please act swiftly to"
  ]
};

export const pointIntroVariants = [
  "Consider that",
  "It is important to note that",
  "We must remember that",
  "The fact remains that",
  "It is clear that",
  "Research shows that",
  "Evidence indicates that",
  "It is a reality that",
  "We cannot ignore that",
  "It is well-documented that",
  "The truth is that",
  "It has been shown that",
  "We must acknowledge that",
  "It is undeniable that",
  "The data supports that",
  "It is a key point that",
  "We should highlight that",
  "It is significant that",
  "The reality on the ground is that",
  "It is crucial to understand that"
];

export const pointParaphraseFrames = [
  "I’m asking you to consider that {pointMeaning}.",
  "It matters because {pointMeaning}.",
  "This area is important since {pointMeaning}.",
  "We must act because {pointMeaning}.",
  "The stakes are high, as {pointMeaning}.",
  "It is vital to recognize that {pointMeaning}.",
  "A key reason for protection is that {pointMeaning}.",
  "We cannot overlook the fact that {pointMeaning}.",
  "This is critical because {pointMeaning}.",
  "The community values this land since {pointMeaning}.",
  "Protection is necessary because {pointMeaning}.",
  "It is essential to understand that {pointMeaning}.",
  "The significance of this cannot be overstated: {pointMeaning}.",
  "We are concerned because {pointMeaning}.",
  "This matters deeply, given that {pointMeaning}.",
  "It is a priority because {pointMeaning}.",
  "The urgency stems from the fact that {pointMeaning}.",
  "We must prioritize this since {pointMeaning}.",
  "This is a pressing issue because {pointMeaning}.",
  "The need for conservation is clear: {pointMeaning}."
];

export const alternativesSentences = [
  "Housing should be built on already-developed sites like empty commercial parcels, not on irreplaceable forest trails.",
  "We support housing, but it belongs on closed institutional sites or dead malls, not in our woodlands.",
  "Please prioritize housing on disturbed lands and former facilities instead of destroying recreational forests.",
  "While housing is needed, we must utilize empty commercial sites rather than clearing vital community forests.",
  "New development should target already-developed areas like closed campuses, preserving our natural woodland sanctuaries.",
  "It makes sense to build on dead malls and former facilities, not on irreplaceable forested land.",
  "We must balance housing needs by building on disturbed sites, leaving our recreational forests intact.",
  "Housing belongs on already-developed parcels, such as empty commercial spaces, rather than our precious woodlands.",
  "Let's prioritize development on closed institutional sites instead of sacrificing the forests our community relies on.",
  "Building on former facilities and dead malls is a better choice than destroying irreplaceable forest trails.",
  "We can meet housing goals using already-developed sites without losing the woodlands we use daily.",
  "Please direct new housing to empty commercial parcels and preserve our vital recreational forest land."
];
